### ISSUE TITLE
New message from ""

### ISSUE THREAD

**Issue by ejrr** [Softdiscover/Zigaform-WP-Form-Builder-Lite#3]
Good Morning,
some submissions come empty, bring only email and subject only with New message from ""

What could be wrong? Many thanks for future help.

Email: blablabla@gmail.com

---

Date: 30/07/2020
Time: 00:58
Page URL: https://blabla.com/blabla/
User Agent: Mozilla/5.0 (Linux; Android 10; SM-A750FN) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Mobile Safari/537.36

**Comment by larangin** [comment]
hello, first upgrade to latest version and check again.
